name: "Test"

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  test:
    name: "Test"
    runs-on: "ubuntu-latest"
    steps:
        - name: "Checkout the repository"
          uses: "actions/checkout@v4.2.2"

        - name: "Set up Python"
          uses: actions/setup-python@v5.2.0
          with:
            python-version: "3.11"
            cache: "pip"

        - name: "Install requirements"
          run: python3 -m pip install -r requirements.txt

        - name: "Run"
          run: python3 -m pytest --cov=./ --cov-report=xml --cov-fail-under=80 -v

        - name: Upload coverage reports to Codecov
          uses: codecov/codecov-action@v4.6.0
          with:
            token: ${{ secrets.CODECOV_TOKEN }}
